apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bj6w
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0071-tenant/tkrw-pr712-0075-0071-app/devfile-sample-bj6w@sha256:18ce835e199ba74943c241830fc859ec890b03a92ca30edc14be4efbe1df95d1
        name: my-nodejs
        resources: {}
status: {}
